apiVersion: v2
name: istio
description: deploy istio
type: application
version: 0.1.0

dependencies:
  - name: base
    repository: https://istio-release.storage.googleapis.com/charts
    version: 1.19.3
  - name: istiod
    repository: https://istio-release.storage.googleapis.com/charts
    version: 1.19.0
  - name: kiali-server
    repository: https://kiali.org/helm-charts
    version: 1.73.0